version: "3.7"
services:
  hazmisr_admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin
    restart: always
    ports:
      - "8080"
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - VIRTUAL_PORT=8080
    networks:
      - webproxy
networks:
  webproxy:
    external: true
